; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_title:=music_title

music_title:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : prismaria-title
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_title
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env4,@env6,@env2 ; 00 : keyboard
	.word @env1,@env4,@env7,@env3 ; 01 : voice

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cc,$7f,$00,$02
@env2:
	.byte $00,$c0,$c1,$c2,$c1,$bf,$be,$bf,$c0,$00,$08
@env3:
	.byte $00,$c3,$c2,$c1,$c0,$c1,$c0,$c1,$c0,$00,$08
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00
@env7:
	.byte $c1,$7f,$00,$00
@env8:
	.byte $00,$c2,$c4,$c5,$02,$c4,$c4,$c1,$00,$07

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $2e, $cd, $31, $cd, $2e, $cd, $31, $cd
@song0ref14:
	.byte $48, $2c, $91, $00, $91, $2c, $91, $00, $91, $30, $cd, $2c, $cd, $27, $cd
@song0ref29:
	.byte $48, $2a, $91, $00, $91, $2a, $91, $00, $91, $2a, $91, $00, $91, $2a, $91, $00, $91, $2e, $91, $00, $91, $2e, $91, $00
	.byte $91, $2e, $91, $00, $91, $2e, $91, $00, $91, $48, $31, $91, $00, $91, $31, $91, $00, $91, $31, $91, $00, $91, $31, $91
	.byte $00, $91, $30, $91, $00, $91, $30, $91, $00, $91, $30, $91, $00, $91, $30, $91, $00, $91
	.byte $41, $40
	.word @song0ref29
	.byte $41, $40
	.word @song0ref29
	.byte $41, $40
	.word @song0ref29
	.byte $41, $40
	.word @song0ref29
	.byte $41, $40
	.word @song0ref29
	.byte $41, $0e
	.word @song0ref14
	.byte $48, $22, $cd, $26, $cd, $29, $a5, $27, $f5, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $19, $ff, $9d, $20, $ff, $9d
@song0ref133:
	.byte $1d, $cd, $18, $cd, $14, $cd, $11, $cd
@song0ref141:
	.byte $19, $ff, $9d, $20, $ff, $9d, $22, $ff, $9d, $20, $ff, $9d
	.byte $41, $0c
	.word @song0ref141
	.byte $41, $0c
	.word @song0ref141
	.byte $41, $0c
	.word @song0ref141
	.byte $41, $0c
	.word @song0ref141
	.byte $41, $0c
	.word @song0ref141
	.byte $41, $0e
	.word @song0ref133
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $82
@song0ref182:
	.byte $2e, $91, $00, $91, $2e, $91, $00, $ff, $ff, $81, $2e, $91, $00, $91, $2e, $91, $00, $ff, $ff, $81
	.byte $41, $14
	.word @song0ref182
	.byte $2e, $b9, $00, $91, $2e, $a5, $35, $ff, $c5, $2e, $b9
@song0ref216:
	.byte $00, $91, $35, $91, $00, $91, $35, $91, $00, $91, $35, $91
	.byte $41, $0c
	.word @song0ref216
	.byte $00, $91, $2e, $b9, $00, $91, $2e, $a5, $35, $ff, $c5, $36, $cd, $35, $cd, $33, $cd, $35, $91, $00, $91, $35, $91, $00
	.byte $91
	.byte $41, $14
	.word @song0ref182
	.byte $41, $14
	.word @song0ref182
	.byte $36, $a5, $00, $a5, $35, $a5, $00, $a5, $35, $91
	.byte $41, $0c
	.word @song0ref216
	.byte $00, $91, $2e, $91, $00, $91, $2e, $91, $00, $ff, $ff, $81, $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
@song0ref292:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref292
	.byte $41, $0c
	.word @song0ref292
	.byte $41, $0c
	.word @song0ref292
	.byte $42
	.word @song0ch3loop
