; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_level_one

music_level_one:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_level_one
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env6,@env9,@env0 ; 00 : S2
	.word @env10,@env4,@env9,@env3 ; 01 : D1
	.word @env5,@env7,@env8,@env1 ; 02 : S1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$bf,$c0,$00,$03
@env2:
	.byte $00,$cc,$ca,$c7,$c5,$00,$04
@env3:
	.byte $00,$bf,$b9,$be,$be,$c5,$c7,$c4,$c1,$00,$08
@env4:
	.byte $c3,$c2,$c1,$c0,$00,$03
@env5:
	.byte $00,$c2,$c0,$c1,$c0,$c1,$c2,$c0,$c1,$00,$08
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $c0,$b8,$c0,$00,$02
@env8:
	.byte $7f,$00,$00
@env9:
	.byte $c1,$7f,$00,$00
@env10:
	.byte $00,$c1,$7f,$00,$02

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $84
@song0ref6:
	.byte $2e, $8b, $00, $8b, $2a, $8b, $00, $99, $31, $8b, $00, $99, $2e, $8b, $00, $a7, $2a, $8b, $00, $8b, $2e, $8b, $00, $8b
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $48
	.byte $41, $18
	.word @song0ref6
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $00, $8b, $80
@song0ref97:
	.byte $33, $8b, $00, $99, $38, $8b, $00, $8b, $33, $8b, $00, $99, $38, $8b, $00, $8b, $33, $8b, $00, $8b, $38, $8b, $00, $8b
	.byte $33, $8b, $00, $8b
	.byte $41, $1b
	.word @song0ref97
	.byte $ff, $dd, $2e, $d1, $00, $99, $33, $99, $00, $99, $2e, $99, $00, $99, $2e, $b5, $00, $8b, $31, $8b, $33, $8b, $00, $8b
	.byte $35, $99, $00, $99, $2e, $99, $00, $99, $2e, $d1, $00, $99, $36, $99, $00, $99, $2e, $99, $00, $99, $2e, $d1, $00, $99
	.byte $38, $99, $00, $99, $36
@song0ref181:
	.byte $a7, $00, $8b, $35, $8b, $00, $8b, $33, $c3, $00, $8b, $31, $d1, $00, $99, $3a, $99, $00, $99, $38, $99, $00, $99, $38
	.byte $99, $38, $99, $00, $99, $36, $99, $35, $8b, $00, $8b, $33, $c3, $00, $8b, $31, $d1, $00, $99, $38, $99, $00, $99, $38
	.byte $99, $00, $99, $38, $99, $00, $99, $3a
	.byte $41, $0f
	.word @song0ref181
	.byte $35, $8b, $00, $8b, $33, $c3, $00, $8b, $31, $d1, $00, $99, $35, $8b, $00, $8b, $33, $c3, $00, $8b, $35, $d1, $00, $99
	.byte $00, $8b
	.byte $41, $1c
	.word @song0ref97
	.byte $41, $1a
	.word @song0ref97
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $84
@song0ref277:
	.byte $2e, $8b, $00, $a7, $03, $8b, $00, $df, $01, $8b, $00, $a7, $2e, $8b, $00, $a7, $03, $8b, $00, $df, $01, $8b, $00, $a7
	.byte $41, $18
	.word @song0ref277
	.byte $41, $18
	.word @song0ref277
	.byte $41, $18
	.word @song0ref277
	.byte $41, $18
	.word @song0ref277
	.byte $41, $18
	.word @song0ref277
	.byte $41, $18
	.word @song0ref277
	.byte $41, $18
	.word @song0ref277
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref326:
	.byte $82, $27, $8b, $24, $8b, $20, $8b, $00, $8b, $27, $8b, $00, $8b, $80, $22, $8b, $00, $8b, $82, $25, $8b, $00, $8b, $24
	.byte $8b, $00, $8b, $27, $8b, $80, $22, $8b, $20, $8b, $00, $8b
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $41, $20
	.word @song0ref326
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref411:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
	.byte $41, $10
	.word @song0ref411
	.byte $42
	.word @song0ch4loop
